language: java
jdk:
  - openjdk8
  
# whitelist
branches:
  only:
    - 3.10.x
    - /^ecat3.10-.*$/ # any dev branch
    - ecat-test # test branch
    
script:
  - if [[ $TRAVIS_BRANCH =~ ^ecat3.10-.*$ ]]; then export BRANCH=/ecat3/dev; elif [[ $TRAVIS_BRANCH = ecat-test ]]; then export BRANCH=/ecat3/test; else export BRANCH=/ecat3/prod; fi
  - mvn clean install -DskipTests -Penv-prod,es

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: $BRANCH
    