name: eCat cicd

on: 
  push:
    branches:
      - devtw-github-actions
      - ecat-test
      - 3.10.x
  # Optimise action runs: restrict PR only to Prod.
  pull_request:
    branches:
      - 3.10.x

jobs:
  build-deploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        java-package: 'jdk'
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # - name: Build with Maven
    #   run: mvn clean install -DskipTests -Penv-prod,es

    - name: Deploy to AWS S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Config and deploy dev branch
      if: github.ref == 'refs/heads/devtw-github-actions'
      run: aws s3 sync --exclude '*' --include 'web/README.md' . s3://ga-rdf-stage-dev
    - name: Config and deploy test branch
      if: github.ref == 'refs/heads/ecat-test'
      run: aws s3 sync --exclude '*' --include 'web/target/geonetwork.war' . s3://tw-aws-s3-bucket/test

    - name: Config and deploy prod branch
      if: github.ref == 'refs/heads/3.10.x'
      run: aws s3 sync --exclude '*' --include 'web/target/geonetwork.war' . s3://tw-aws-s3-bucket/prod
